/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eroshetta;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.*;
import javax.persistence.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Mouaz
 */
public class Eroshetta extends javax.swing.JFrame {

    /**
     * Creates new form Eroshetta
     */
    final static EntityManagerFactory emf = Persistence.createEntityManagerFactory("EroshettaPU");
    static EntityManager em = emf.createEntityManager();

    public Eroshetta() {
        initComponents();
        //run methode
        this.jTextFieldSearchDrags.setText("");
        String query = this.jTextFieldSearchDrags.getText();
        final ArrayList<Drugs> finos = Eroshetta.drug_search(query);
        final ArrayList<String> s = new ArrayList();
        for (int i = 0; i < finos.size(); i++) {
//                this.jArrayList_Drugs.(finos.get(i).getTradeName());
            if (finos.get(i).getTradeName() != null || finos.get(i).getClassName() != null) {
                s.add(finos.get(i).getTradeName() + "(" + finos.get(i).getClassName() + ")");
            }

        }
        jList_Drugs.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return finos.size();
            }

            public Object getElementAt(int i) {
                return finos.get(i);
            }
        });
        // doctor attributes malaksh da3wa beha for prescription
        Query qr = em.createNamedQuery("Doctor.findAll");
        List <Doctor> tmpList = qr.getResultList();
        Doctor d = tmpList.get(0);
        this.DoctorName.setText("Dr."+ d.getName());
        this.DoctorAddresse.setText("Addresse : "+d.getAddress());
        this.DoctorMobileNo.setText("Mobile no : "+d.getMobileNo().toString());
        this.DoctorOfficeNo.setText("Office no : "+d.getOfficeNo().toString());
        // a5erha
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanelPatientsBook = new javax.swing.JPanel();
        jScrollPanePatientsBook = new javax.swing.JScrollPane();
        jListPatientsBook = new javax.swing.JList();
        jTextFieldPatientsBook = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanelPatientOldPresc = new javax.swing.JPanel();
        jPanelPatientProfile = new javax.swing.JPanel();
        jLabelPatientProfileName = new javax.swing.JLabel();
        jLabelPatientProfileGender = new javax.swing.JLabel();
        jLabelPatientProfileBirthday = new javax.swing.JLabel();
        jLabelPatientProfileMaritalStatus = new javax.swing.JLabel();
        jLabelPatientProfilePregnant = new javax.swing.JLabel();
        jLabelPatientProfileHeight = new javax.swing.JLabel();
        jLabelPatientProfileWeight = new javax.swing.JLabel();
        jLabelPatientProfileBMI = new javax.swing.JLabel();
        jLabelPatientProfileCurrentMedication = new javax.swing.JLabel();
        jLabelPatientProfileDiagnosis = new javax.swing.JLabel();
        jTextFieldPatientProfileName = new javax.swing.JTextField();
        jComboBoxPatientProfileGender = new javax.swing.JComboBox();
        jComboBoxPatientProfileDay = new javax.swing.JComboBox();
        jComboBoxPatientProfileMonth = new javax.swing.JComboBox();
        jComboBoxPatientProfileYear = new javax.swing.JComboBox();
        jComboBoxPatientProfileMarital = new javax.swing.JComboBox();
        jComboBoxPatientProfilePregnant = new javax.swing.JComboBox();
        jTextFieldPatientProfileBMI = new javax.swing.JTextField();
        jTextFieldPatientProfileWeight = new javax.swing.JTextField();
        jTextFieldPatientProfileHeight = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Panel_Drugs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearchDrags = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Drugs = new javax.swing.JList();
        drugProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        drugTradeName = new javax.swing.JLabel();
        drugGenericNames = new javax.swing.JLabel();
        drugDosage = new javax.swing.JLabel();
        dosageForm = new javax.swing.JLabel();
        drugRoute = new javax.swing.JLabel();
        drugPrecautions = new javax.swing.JLabel();
        drugHalfLife = new javax.swing.JLabel();
        drugMajor = new javax.swing.JLabel();
        drugMinor = new javax.swing.JLabel();
        drugFoods = new javax.swing.JLabel();
        drugCustomName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelPrescription = new javax.swing.JPanel();
        jPanelDoctorCredentials = new javax.swing.JPanel();
        DoctorName = new javax.swing.JLabel();
        DoctorMobileNo = new javax.swing.JLabel();
        DoctorAddresse = new javax.swing.JLabel();
        DoctorOfficeNo = new javax.swing.JLabel();
        jPanelDoctorCredentials1 = new javax.swing.JPanel();
        PatientName = new javax.swing.JLabel();
        PatientNextVisit = new javax.swing.JLabel();
        PatientBirthDate = new javax.swing.JLabel();
        DoctorOfficeNo1 = new javax.swing.JLabel();
        DoctorOfficeNo2 = new javax.swing.JLabel();
        DoctorOfficeNo3 = new javax.swing.JLabel();
        DrugsInPrescription = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        editDoctorProfile = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eroshetta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelPatientsBook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patients Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        jListPatientsBook.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jListPatientsBook.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListPatientsBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListPatientsBookKeyReleased(evt);
            }
        });
        jScrollPanePatientsBook.setViewportView(jListPatientsBook);

        jTextFieldPatientsBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientsBookActionPerformed(evt);
            }
        });
        jTextFieldPatientsBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPatientsBookKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelPatientsBookLayout = new javax.swing.GroupLayout(jPanelPatientsBook);
        jPanelPatientsBook.setLayout(jPanelPatientsBookLayout);
        jPanelPatientsBookLayout.setHorizontalGroup(
            jPanelPatientsBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePatientsBook, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(jTextFieldPatientsBook)
        );
        jPanelPatientsBookLayout.setVerticalGroup(
            jPanelPatientsBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPatientsBookLayout.createSequentialGroup()
                .addComponent(jTextFieldPatientsBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePatientsBook))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanelPatientOldPresc.setBorder(javax.swing.BorderFactory.createTitledBorder("Old Prescriptions"));

        javax.swing.GroupLayout jPanelPatientOldPrescLayout = new javax.swing.GroupLayout(jPanelPatientOldPresc);
        jPanelPatientOldPresc.setLayout(jPanelPatientOldPrescLayout);
        jPanelPatientOldPrescLayout.setHorizontalGroup(
            jPanelPatientOldPrescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanelPatientOldPrescLayout.setVerticalGroup(
            jPanelPatientOldPrescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jPanelPatientProfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPatientProfileName.setText("Name:");

        jLabelPatientProfileGender.setText("Gender:");

        jLabelPatientProfileBirthday.setText("Birthday:");

        jLabelPatientProfileMaritalStatus.setText("Marital Status:");

        jLabelPatientProfilePregnant.setText("Pregnant:");

        jLabelPatientProfileHeight.setText("Height:");

        jLabelPatientProfileWeight.setText("Weight:");

        jLabelPatientProfileBMI.setText("BMI:");

        jLabelPatientProfileCurrentMedication.setText("Current Medications:");

        jLabelPatientProfileDiagnosis.setText("Diagnosis:");

        jTextFieldPatientProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientProfileNameActionPerformed(evt);
            }
        });

        jComboBoxPatientProfileGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        DefaultComboBoxModel modelComboBoxDay = new DefaultComboBoxModel();
        jComboBoxPatientProfileDay.setModel(modelComboBoxDay
        );
        int year = Calendar.getInstance().get(Calendar.YEAR);
        for(int i=1; i<32; i++ ){
            modelComboBoxDay.addElement(i);
        }
        jComboBoxPatientProfileDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxPatientProfileDayMouseClicked(evt);
            }
        });

        jComboBoxPatientProfileMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxPatientProfileMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPatientProfileMonthActionPerformed(evt);
            }
        });

        DefaultComboBoxModel modelComboBoxYear = new DefaultComboBoxModel();
        jComboBoxPatientProfileYear.setModel(modelComboBoxYear
        );
        for(int i=Calendar.getInstance().get(Calendar.YEAR); i>=1970; i--){
            modelComboBoxYear.addElement(i);
        }
        jComboBoxPatientProfileYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPatientProfileYearActionPerformed(evt);
            }
        });

        jComboBoxPatientProfileMarital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPatientProfilePregnant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldPatientProfileBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientProfileBMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPatientProfileLayout = new javax.swing.GroupLayout(jPanelPatientProfile);
        jPanelPatientProfile.setLayout(jPanelPatientProfileLayout);
        jPanelPatientProfileLayout.setHorizontalGroup(
            jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPatientProfileGender)
                    .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPatientProfileCurrentMedication)
                        .addComponent(jLabelPatientProfileName, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPatientProfileDiagnosis, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPatientProfileBMI, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPatientProfileMaritalStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPatientProfileBirthday, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPatientProfileHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPatientProfileName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPatientProfileLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                                .addComponent(jTextFieldPatientProfileBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPatientProfileWeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPatientProfileWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPatientProfileHeight))
                            .addComponent(jComboBoxPatientProfileGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                                .addComponent(jComboBoxPatientProfileDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPatientProfileMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPatientProfileYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                                .addComponent(jComboBoxPatientProfileMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPatientProfilePregnant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPatientProfilePregnant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPatientProfileLayout.setVerticalGroup(
            jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientProfileLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientProfileName)
                    .addComponent(jTextFieldPatientProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientProfileGender)
                    .addComponent(jComboBoxPatientProfileGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientProfileBirthday)
                    .addComponent(jComboBoxPatientProfileDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPatientProfileMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPatientProfileYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientProfileMaritalStatus)
                    .addComponent(jComboBoxPatientProfileMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPatientProfilePregnant)
                    .addComponent(jComboBoxPatientProfilePregnant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelPatientProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientProfileBMI)
                    .addComponent(jLabelPatientProfileWeight)
                    .addComponent(jLabelPatientProfileHeight)
                    .addComponent(jTextFieldPatientProfileBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPatientProfileWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPatientProfileHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabelPatientProfileCurrentMedication)
                .addGap(92, 92, 92)
                .addComponent(jLabelPatientProfileDiagnosis)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPatientProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPatientOldPresc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanelPatientOldPresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPatientProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Patient Profile", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Drugs");

        jTextFieldSearchDrags.setText("jTextField1");
        jTextFieldSearchDrags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchDragsActionPerformed(evt);
            }
        });
        jTextFieldSearchDrags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchDragsKeyReleased(evt);
            }
        });

        jList_Drugs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_Drugs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_DrugsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Drugs);

        drugProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Drug profile"));
        drugProfile.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel2.setText("Custom name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel3.setText("Trade name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel4.setText("Dosage:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel5.setText("Dosage form:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel6.setText("Route of elimination:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel7.setText("Precautions:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel8.setText("Half life:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel9.setText("Generic names:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel10.setText("Major side effects:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel11.setText("Minor side effects:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel12.setText("Interactive foods:");

        drugTradeName.setText("jLabel14");

        drugGenericNames.setText("jLabel15");

        drugDosage.setText("jLabel16");

        dosageForm.setText("jLabel17");

        drugRoute.setText("jLabel18");

        drugPrecautions.setText("jLabel19");

        drugHalfLife.setText("jLabel20");

        drugMajor.setText("jLabel21");

        drugMinor.setText("jLabel22");

        drugFoods.setText("jLabel23");

        drugCustomName.setText("jLabel24");

        jButton1.setText("+");

        javax.swing.GroupLayout drugProfileLayout = new javax.swing.GroupLayout(drugProfile);
        drugProfile.setLayout(drugProfileLayout);
        drugProfileLayout.setHorizontalGroup(
            drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugGenericNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugDosage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dosageForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugRoute, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugPrecautions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugHalfLife, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugMajor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugMinor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugTradeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugCustomName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        drugProfileLayout.setVerticalGroup(
            drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugProfileLayout.createSequentialGroup()
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(drugCustomName)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drugTradeName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(drugGenericNames))
                .addGap(2, 2, 2)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drugDosage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dosageForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(drugRoute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(drugPrecautions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(drugHalfLife))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(drugMajor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(drugMinor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drugProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(drugFoods))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_DrugsLayout = new javax.swing.GroupLayout(Panel_Drugs);
        Panel_Drugs.setLayout(Panel_DrugsLayout);
        Panel_DrugsLayout.setHorizontalGroup(
            Panel_DrugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrugsLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(117, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(drugProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldSearchDrags, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Panel_DrugsLayout.setVerticalGroup(
            Panel_DrugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrugsLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearchDrags, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drugProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPrescription.setAutoscrolls(true);

        jPanelDoctorCredentials.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDoctorCredentials.setAutoscrolls(true);

        DoctorName.setText("jLabel14");

        DoctorMobileNo.setText("jLabel14");

        DoctorAddresse.setText("jLabel14");

        DoctorOfficeNo.setText("jLabel14");

        javax.swing.GroupLayout jPanelDoctorCredentialsLayout = new javax.swing.GroupLayout(jPanelDoctorCredentials);
        jPanelDoctorCredentials.setLayout(jPanelDoctorCredentialsLayout);
        jPanelDoctorCredentialsLayout.setHorizontalGroup(
            jPanelDoctorCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorCredentialsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDoctorCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorName)
                    .addComponent(DoctorMobileNo)
                    .addComponent(DoctorAddresse)
                    .addComponent(DoctorOfficeNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDoctorCredentialsLayout.setVerticalGroup(
            jPanelDoctorCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorCredentialsLayout.createSequentialGroup()
                .addComponent(DoctorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorAddresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorMobileNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorOfficeNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDoctorCredentials1.setBorder(new javax.swing.border.MatteBorder(null));

        PatientName.setText("jLabel14");

        PatientNextVisit.setText("jLabel14");

        PatientBirthDate.setText("jLabel14");

        DoctorOfficeNo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DoctorOfficeNo1.setText("Patient Name : ");

        DoctorOfficeNo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DoctorOfficeNo2.setText("Birth Date : ");

        DoctorOfficeNo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DoctorOfficeNo3.setText("Next Visit : ");

        javax.swing.GroupLayout jPanelDoctorCredentials1Layout = new javax.swing.GroupLayout(jPanelDoctorCredentials1);
        jPanelDoctorCredentials1.setLayout(jPanelDoctorCredentials1Layout);
        jPanelDoctorCredentials1Layout.setHorizontalGroup(
            jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorCredentials1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorOfficeNo1)
                    .addComponent(DoctorOfficeNo3)
                    .addComponent(DoctorOfficeNo2))
                .addGap(76, 76, 76)
                .addGroup(jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientName)
                    .addComponent(PatientNextVisit)
                    .addComponent(PatientBirthDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDoctorCredentials1Layout.setVerticalGroup(
            jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorCredentials1Layout.createSequentialGroup()
                .addGroup(jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientName)
                    .addComponent(DoctorOfficeNo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientBirthDate)
                    .addComponent(DoctorOfficeNo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorCredentials1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientNextVisit)
                    .addComponent(DoctorOfficeNo3))
                .addGap(23, 23, 23))
        );

        DrugsInPrescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Drugs"));
        DrugsInPrescription.setAutoscrolls(true);

        javax.swing.GroupLayout DrugsInPrescriptionLayout = new javax.swing.GroupLayout(DrugsInPrescription);
        DrugsInPrescription.setLayout(DrugsInPrescriptionLayout);
        DrugsInPrescriptionLayout.setHorizontalGroup(
            DrugsInPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DrugsInPrescriptionLayout.setVerticalGroup(
            DrugsInPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jButton2.setText("Preview for saving and printing");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("Notes : ");

        javax.swing.GroupLayout jPanelPrescriptionLayout = new javax.swing.GroupLayout(jPanelPrescription);
        jPanelPrescription.setLayout(jPanelPrescriptionLayout);
        jPanelPrescriptionLayout.setHorizontalGroup(
            jPanelPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDoctorCredentials1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DrugsInPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrescriptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addComponent(jTextField1)
            .addGroup(jPanelPrescriptionLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelDoctorCredentials, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPrescriptionLayout.setVerticalGroup(
            jPanelPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrescriptionLayout.createSequentialGroup()
                .addComponent(jPanelDoctorCredentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDoctorCredentials1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrugsInPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setText("New Prescription");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel15)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Panel_Drugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Drugs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("New Prescription", jPanel5);

        fileMenu.setText("File");
        jMenuBar2.add(fileMenu);

        editMenu.setText("Edit");

        editDoctorProfile.setText("Profile");
        editDoctorProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDoctorProfileActionPerformed(evt);
            }
        });
        editMenu.add(editDoctorProfile);

        jMenuBar2.add(editMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jPanelPatientsBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPatientsBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jListPatientsBookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListPatientsBookKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jListPatientsBookKeyReleased

    private void jTextFieldPatientsBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientsBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientsBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static ArrayList<Drugs> drug_search(String s) {

        //inserting all names in ArrayLists to search with piriority
//        em.getTransaction().begin();
        Drugs example = new Drugs();
        example.setClassName("class Name");
        example.setClassName("trade Name");
        example.setClassName("generic Name");
        em.persist(example);
        ArrayList<String> tradeNames = new ArrayList();
        ArrayList<String> genericNames = new ArrayList();
        ArrayList<String> classNames = new ArrayList();
        Query q = em.createNamedQuery("Drugs.findAll");
        List<Drugs> allDrugsList = q.getResultList();
        ArrayList<Drugs> allDrugs = new ArrayList();
        allDrugs.addAll(allDrugsList);
        for (int i = 0; i < allDrugs.size(); i++) {
            tradeNames.add(allDrugs.get(i).getTradeName());
            classNames.add(allDrugs.get(i).getClassName());

            q = em.createNamedQuery("GenericNames.findByDrugId").setParameter("drugId", allDrugs.get(i).getId());
            List<GenericNames> tmpList = q.getResultList();
            ArrayList<GenericNames> tmp = new ArrayList();
            tmp.addAll(tmpList);
//        g = l.get(i).getGenericNames();
            for (int j = 0; j < tmp.size(); j++) {
                genericNames.add(tmp.get(j).getGenericName());
            }
        }
        System.out.println("trade names : " + tradeNames);
        System.out.println("class names : " + classNames);
        System.out.println("generic names : " + genericNames);
        //stop ArrayListing
        ArrayList<String> tradeNamesTopResults = new <String>ArrayList();
        tradeNamesTopResults = Eroshetta.topResults(s, tradeNames);
        ArrayList<String> classNamesTopResults = new <String>ArrayList();
        classNamesTopResults = Eroshetta.topResults(s, classNames);
        ArrayList<String> genericNamesTopResults = new <String>ArrayList();
        genericNamesTopResults = Eroshetta.topResults(s, genericNames);
        ArrayList<Drugs> drugsTopWithTradeName = new <Drugs>ArrayList();
        ArrayList<Drugs> drugsTopWithClassName = new <Drugs>ArrayList();
        ArrayList<Drugs> drugsTopWithGenericNames = new <Drugs>ArrayList();
        ArrayList<GenericNames> drugsWithCertainGeneric = new <Drugs>ArrayList();

        if (tradeNamesTopResults != null) {
            for (int b = 0; b < tradeNamesTopResults.size(); b++) {
                q = em.createNamedQuery("Drugs.findByTradeName").setParameter("tradeName", tradeNamesTopResults.get(b));
//            ArrayList<Drugs> resultSet = q.getResultArrayList();
                drugsTopWithTradeName.addAll(q.getResultList());
            }
        }
        if (classNamesTopResults != null) {
            for (int b = 0; b < classNamesTopResults.size(); b++) {
                q = em.createNamedQuery("Drugs.findByClassName").setParameter("className", classNamesTopResults.get(b));
                drugsTopWithClassName.addAll(q.getResultList());
            }
        }
        if (genericNamesTopResults != null) {
            for (int b = 0; b < genericNamesTopResults.size(); b++) {
                q = em.createNamedQuery("GenericNames.findByGenericName").setParameter("genericName", genericNamesTopResults.get(b));
                List<GenericNames> drugsWithCertainGenericList = q.getResultList();
                drugsWithCertainGeneric.addAll(drugsWithCertainGenericList);
                for (int e = 0; e < drugsWithCertainGeneric.size(); e++) {
                    Drugs d = em.find(Drugs.class, drugsWithCertainGeneric.get(e).getDrugId());
                    drugsTopWithGenericNames.add(d);
                }
            }
        }

        ArrayList<Drugs> finalResult = new ArrayList();
        if (drugsTopWithGenericNames != null) {
            drugsTopWithClassName.addAll(drugsTopWithGenericNames);
        }
        if (drugsTopWithClassName != null) {
            drugsTopWithTradeName.addAll(drugsTopWithClassName);
        }
//            if(drugsTopWithTradeName != null){
        finalResult.addAll(drugsTopWithTradeName);
//            }
//            if(allDrugs != new ArrayList()){
//        finalResult.addAll(allDrugs);
//            }
        for (int o = 0; o < finalResult.size(); o++) {
            Drugs nowDrug = finalResult.get(o);
//             int existenceAndIndex = 0;
//           if(finalResult.size()!=allDrugs.size()){
            System.out.println("nowDrug ID" + o);
            for (int i = finalResult.size() - 1; i > o; i--) {
                if (finalResult.get(i).getId() == nowDrug.getId()) {
                    finalResult.remove(i);
                    System.out.println("the index wich" + i);
                }
            }
            System.out.println(finalResult);
//                   if(finalResult.subList(o+1, finalResult.size()).contains(nowDrug)){
//                   finalResult.remove(nowDrug);
//                   
//               }

//               }

//           }
        }

//        }catch(NullPointerException e){
//            System.out.println("Searching>>")
//        }
//         System.out.println("trade names : "+tradeNamesTopResults);
//         System.out.println("class names : "+classNamesTopResults);
//         System.out.println("generic names : "+genericNamesTopResults);
        return finalResult;
    }

    public static ArrayList<String> topResults(String query, ArrayList<String> field) {
        ArrayList<String> match = new ArrayList();
        System.out.println("fild is empty??" + field.isEmpty() + "with size" + field.size() + "and attributes" + field);
        if (field != null) {
            System.out.println("ew3a ;)");
            for (int k = 0; k < field.size(); k++) {
                try {
                    if (query.equalsIgnoreCase(field.get(k).substring(0, query.length()))) {
//            if(field.get(k).contains(query)){
                        System.out.print(query);
                        match.add(field.get(k));
                    }
                } catch (Exception e) {
                }

            }

//           if(match.size()<field.size()){
//               for(int a =0;a<field.size();a++){
//                   if(!match.contains(field.get(a))){
//                       match.add(field.get(a));
//                   }
//               }
//           }

        }
        System.out.println("matched is " + match);
        return match;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Query q = em.createNamedQuery("Patients.findAll");
        patientsBookList = (List<Patients>) q.getResultList();
        DefaultListModel model = new DefaultListModel();
        jListPatientsBook.setModel(model);
        for (int i = 0; i < patientsBookList.size(); i++) {
            model.add(i, patientsBookList.get(i).getName());
        }

    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldPatientsBookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPatientsBookKeyReleased
        // TODO add your handling code here:
        Query q = em.createNamedQuery("Patients.findByName");
        q.setParameter("pName", jTextFieldPatientsBook.getText() + "%");
        patientsBookList = (List<Patients>) q.getResultList();
        DefaultListModel model = new DefaultListModel();
        jListPatientsBook.setModel(model);
        for (int i = 0; i < patientsBookList.size(); i++) {
            model.add(i, patientsBookList.get(i).getName());
        }
    }//GEN-LAST:event_jTextFieldPatientsBookKeyReleased

    private void jTextFieldPatientProfileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientProfileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientProfileNameActionPerformed

    private void jTextFieldPatientProfileBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientProfileBMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientProfileBMIActionPerformed

    private void jComboBoxPatientProfileMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPatientProfileMonthActionPerformed
        // TODO add your handling code here:
        this.leapYearModification();
    }//GEN-LAST:event_jComboBoxPatientProfileMonthActionPerformed

    private void jComboBoxPatientProfileDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPatientProfileDayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPatientProfileDayMouseClicked

    private void jTextFieldSearchDragsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchDragsKeyReleased
        String query = this.jTextFieldSearchDrags.getText();
        final ArrayList<Drugs> finos = Eroshetta.drug_search(query);
        final ArrayList<String> s = new ArrayList();
        for (int i = 0; i < finos.size(); i++) {
//                this.jArrayList_Drugs.(finos.get(i).getTradeName());
            if (finos.get(i).getTradeName() != null || finos.get(i).getClassName() != null) {
                s.add(finos.get(i).getTradeName() + "(" + finos.get(i).getClassName() + ")");
            }

        }
        jList_Drugs.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return finos.size();
            }

            public Object getElementAt(int i) {
                return finos.get(i);
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchDragsKeyReleased

    private void editDoctorProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDoctorProfileActionPerformed
        // TODO add your handling code here:
        DoctorInfo info = new DoctorInfo();
        info.setVisible(true);
        info.setDefaultCloseOperation(info.EXIT_ON_CLOSE);
    }//GEN-LAST:event_editDoctorProfileActionPerformed

    private void jTextFieldSearchDragsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchDragsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchDragsActionPerformed

    private void jList_DrugsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_DrugsValueChanged
        // TODO add your handling code here:
        Drugs d = (Drugs) this.jList_Drugs.getSelectedValue();
        int drugId = d.getId();
        System.out.println(drugId);
    }//GEN-LAST:event_jList_DrugsValueChanged

    private void jComboBoxPatientProfileYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPatientProfileYearActionPerformed
        // TODO add your handling code here:
        this.leapYearModification();
        
    }//GEN-LAST:event_jComboBoxPatientProfileYearActionPerformed

    public void leapYearModification() {
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int selectedYear = (Integer) jComboBoxPatientProfileYear.getSelectedItem();
        int selectedMonth = (Integer) jComboBoxPatientProfileMonth.getSelectedIndex() + 1;
        boolean leapYearFlag;
        DefaultComboBoxModel dayModelLeapYead = new DefaultComboBoxModel();
        jComboBoxPatientProfileDay.setModel(dayModelLeapYead);

        if ((selectedYear % 4 == 0) && (selectedYear % 100 != 0) || (selectedYear % 400 == 0)) {
            leapYearFlag = true;
        } else {
            leapYearFlag = false;
        }
        if (selectedMonth == 1 || selectedMonth == 3 || selectedMonth == 5 || selectedMonth == 7 || selectedMonth == 8 || selectedMonth == 10 || selectedMonth == 12) {
            for (int i = 1; i < 32; i++) {
                dayModelLeapYead.addElement(i);
            }
        } else {
            if (selectedMonth == 4 || selectedMonth == 6 || selectedMonth == 9 || selectedMonth == 11) {
                for (int i = 1; i < 31; i++) {
                    dayModelLeapYead.addElement(i);
                }
            } else {
                if (selectedMonth == 2 && leapYearFlag) {
                    for (int i = 1; i < 30; i++) {
                        dayModelLeapYead.addElement(i);
                    }
                } else {
                    for (int i = 1; i < 29; i++) {
                        dayModelLeapYead.addElement(i);
                    }
                }
            }
        }
    }

    public static void createPatients() {
        em.getTransaction().begin();
        for (int i = 0; i < 25; i++) {

            Patients p = new Patients();
            p.setName("Patient" + i);
            em.persist(p);

        }

        em.getTransaction().commit();

    }

    public static void findAllPatients() {

        Query q = em.createNamedQuery("Patients.findByName");
        q.setParameter("pName", "P%");

        patientsBookList = (List<Patients>) q.getResultList();
//         System.out.println();
//         Patients p = l.get(0);
//         System.out.println(p.getName());
//         System.out.println(l.get(0));
//         System.out.println(patientsBookList.toString());
        System.out.println(patientsBookList.size());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eroshetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eroshetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eroshetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eroshetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Eroshetta e = new Eroshetta();
                e.setVisible(true);
//                e.setExtendedState(Frame.MAXIMIZED_BOTH);

            }
        });






//        createPatients();
        findAllPatients();
//        em.close();
//        emf.close();



    }
    static List<Patients> patientsBookList = new ArrayList<Patients>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorAddresse;
    private javax.swing.JLabel DoctorMobileNo;
    private javax.swing.JLabel DoctorName;
    private javax.swing.JLabel DoctorOfficeNo;
    private javax.swing.JLabel DoctorOfficeNo1;
    private javax.swing.JLabel DoctorOfficeNo2;
    private javax.swing.JLabel DoctorOfficeNo3;
    private javax.swing.JPanel DrugsInPrescription;
    private javax.swing.JPanel Panel_Drugs;
    private javax.swing.JLabel PatientBirthDate;
    private javax.swing.JLabel PatientName;
    private javax.swing.JLabel PatientNextVisit;
    private javax.swing.JLabel dosageForm;
    private javax.swing.JLabel drugCustomName;
    private javax.swing.JLabel drugDosage;
    private javax.swing.JLabel drugFoods;
    private javax.swing.JLabel drugGenericNames;
    private javax.swing.JLabel drugHalfLife;
    private javax.swing.JLabel drugMajor;
    private javax.swing.JLabel drugMinor;
    private javax.swing.JLabel drugPrecautions;
    private javax.swing.JPanel drugProfile;
    private javax.swing.JLabel drugRoute;
    private javax.swing.JLabel drugTradeName;
    private javax.swing.JMenuItem editDoctorProfile;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxPatientProfileDay;
    private javax.swing.JComboBox jComboBoxPatientProfileGender;
    private javax.swing.JComboBox jComboBoxPatientProfileMarital;
    private javax.swing.JComboBox jComboBoxPatientProfileMonth;
    private javax.swing.JComboBox jComboBoxPatientProfilePregnant;
    private javax.swing.JComboBox jComboBoxPatientProfileYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPatientProfileBMI;
    private javax.swing.JLabel jLabelPatientProfileBirthday;
    private javax.swing.JLabel jLabelPatientProfileCurrentMedication;
    private javax.swing.JLabel jLabelPatientProfileDiagnosis;
    private javax.swing.JLabel jLabelPatientProfileGender;
    private javax.swing.JLabel jLabelPatientProfileHeight;
    private javax.swing.JLabel jLabelPatientProfileMaritalStatus;
    private javax.swing.JLabel jLabelPatientProfileName;
    private javax.swing.JLabel jLabelPatientProfilePregnant;
    private javax.swing.JLabel jLabelPatientProfileWeight;
    private javax.swing.JList jListPatientsBook;
    private javax.swing.JList jList_Drugs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelDoctorCredentials;
    private javax.swing.JPanel jPanelDoctorCredentials1;
    private javax.swing.JPanel jPanelPatientOldPresc;
    private javax.swing.JPanel jPanelPatientProfile;
    private javax.swing.JPanel jPanelPatientsBook;
    private javax.swing.JPanel jPanelPrescription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanePatientsBook;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldPatientProfileBMI;
    private javax.swing.JTextField jTextFieldPatientProfileHeight;
    private javax.swing.JTextField jTextFieldPatientProfileName;
    private javax.swing.JTextField jTextFieldPatientProfileWeight;
    private javax.swing.JTextField jTextFieldPatientsBook;
    private javax.swing.JTextField jTextFieldSearchDrags;
    // End of variables declaration//GEN-END:variables
}
